name: Build TestDPC APK

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment provided by GitHub Actions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Check out the repository code
        with:
          fetch-depth: 1  # Use a shallow clone for better performance since full history is not required

      - name: Set up JDK
        uses: actions/setup-java@v3  # Set up Java Development Kit (JDK)
        with:
          java-version: '11'  # Use Java 11 for compatibility
          distribution: 'adopt'  # Use AdoptOpenJDK distribution

      - name: Install Bazelisk (Bazel Manager)
        run: |
          # Download the Bazelisk binary (a Bazel version manager)
          sudo curl -Lo /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
          # Verify the integrity of the downloaded file using SHA-256 checksum
          echo "e2a7d25b7c79804d5ab6e72b5a5f3b89c15637f8e91bbed18bfb7be7518f3204  /usr/local/bin/bazel" | sha256sum -c -
          # Make the binary executable
          sudo chmod +x /usr/local/bin/bazel

      - name: Configure Bazel Version
        run: echo "7.4.1" > .bazelversion  # Set the Bazel version to be used

      - name: Verify Bazel Version
        run: bazel --version  # Output the Bazel version to confirm the installation

      - name: Clean Build Environment
        run: |
          # Clean the build environment to remove cached or intermediate files
          bazel clean --expunge

      - name: Build APK
        run: |
          # Build the APK using Bazel
          bazel build //:testdpc

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4  # Upload the built APK as an artifact
        with:
          name: testdpc-apk  # Name the uploaded artifact
          path: "$(bazel info bazel-bin)/testdpc.apk"  # Path to the APK file built by Bazel
