name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Bazel
        run: |
          wget https://github.com/bazelbuild/bazel/releases/download/4.2.1/bazel-4.2.1-linux-x86_64-installer.run
          chmod +x bazel-4.2.1-linux-x86_64-installer.run
          ./bazel-4.2.1-linux-x86_64-installer.run --user

      - name: Build with Bazel
        run: bazel build //:testdpc

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: testdpc-apk
          path: bazel-bin/testdpc.apk
